# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: protoc-gen-go_temporal
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: protoc-gen-go-temporal
    binary: protoc-gen-go_temporal
    main: ./cmd/protoc-gen-go-temporal
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - LICENSE.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: cludden
    name: protoc-gen-go-temporal
signs:
  - artifacts: checksum
