up:
  - go: 1.23.6
  - github-release:
      bufbuild/buf: 1.50.0
      golangci/golangci-lint: 1.63.4
      protocolbuffers/protobuf-go: 1.36.4
      temporalio/cli: 1.3.0
      vektra/mockery: 2.52.4
  - go-install:
      - github.com/alta/protopatch/cmd/protoc-gen-go-patch@v0.5.3
      - github.com/mfridman/tparse@v0.17.0
  - protoc: 29.3
  - custom:
      name: protoc-gen-go_temporal
      meet: |
        mkdir -p ./.omni/bin
        go build -o ./.omni/bin/protoc-gen-go_temporal ./cmd/protoc-gen-go_temporal

path:
  prepend:
    - .omni/bin

commands:
  docs:
    desc: Generate documentation
    run: |
      cd docs && npm run start

  gen:
    desc: Generate code
    run: |
      rm -rf ./gen/**
      buf dep update
      buf format -w
      buf lint
      buf generate
      mockery --log-level=error
      go mod tidy

  genlocal:
    desc: Generate code locally
    run: |
      rm -rf ./gen/**
      buf dep update
      buf format -w
      buf lint
      buf generate --template buf.local.gen.yaml
      mockery --log-level=error
      go mod tidy

  test:
    desc: Run tests
    run: |
      set -o pipefail && go test -json ./... | tparse -all
