name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install omni
        uses: omnicli/setup-action@v0
        with:
          up: true
      
      - name: Run tests
        shell: bash
        run: omni test
        
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./docs/package-lock.json
      - name: Install dependencies
        working-directory: ./docs
        run: npm install
      - name: Test build website
        working-directory: ./docs
        run: npm run build
